### PR TITLE
Several updates

### LINKED ISSUE #21: I trying using the php-clamav but not work.
I trying using the php-clamav but not work.

I'm use the follow code

```php
<?php

require_once 'vendor/autoload.php';

$clam = new Appwrite\ClamAV\Pipe();

echo 'Ping: ';
var_dump($clam->ping());
echo "\n";

echo 'version: ';
var_dump($clam->version());
echo "\n";

echo 'fileScan: ';
var_dump($clam->fileScan('/var/www/html/public/data/tmp/files.txt'));
//var_dump($clam->fileScan('/tmp/files.txt'));
echo "\n";
```

But the log showed.

```
Fri Mar  4 15:09:12 2022 -> /var/www/html/public/data/tmp/files.txt: Can't open file or directory ERROR
```

But, when use the file in /tmp. works

```
Fri Mar  4 15:01:22 2022 -> /tmp/files.txt: Eicar-Signature(69630e4574ec6798239b091cda43dca0:69) FOUND
```

```
root@localhost: ~# namei -lv /var/www/html/public/data/tmp/files.txt
f: /var/www/html//public/data/tmp/files.txt
drwxr-xr-x root     root     /
drwxr-xr-x root     root     var
drwxr-xr-x root     root     www
drwxr-xr-x root     root     html
drwxr-xr-x root     root     public
drwxrwxr-x www-data www-data data
drwxrwxr-x www-data www-data tmp
-rw-r--r-- root     root     files.txt
root@locahost: ~# 
``` 

but not work. Let me known what i'm doing wrong.

other detail, that using clamdscan command work with parameter `--fppass`.

### LINKED ISSUE #23: Please remove virus.txt from /tests/data — it is triggering McAffee and causing entire docker containers to be blocked.
### 👟 Reproduction steps

When trying to transfer docker containers to private servers McAffee blocks the entire container because of this one file. 

### 👍 Expected behavior

There is no reason for such a file to exist in this repo as far as I know?

### 👎 Actual Behavior

N/A

### 🎲 PHP ClamAV version

Version 1.1.x

### 💻 Operating system

Windows

### 🧱 Your Environment

_No response_

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by SoftCreatR**
- Removed test files to prevent triggering AV solutions installed. Instead, use the test class itself to perform the test. This won't test, if ClamAV works properly, but that's nothing this test should cover anyway. Furthermore, the test tried to scan files located in `/home`. I'm somewhat confident, that this fails most of the time (resolves #23)
- Applied PSR-12 related changes
- Set minimum PHP version to 8.0 (analogous to utopia-php/framework)
- Updated travis to test against PHP 8.0 & 8.1, removed PHP 7.1 - 7.4
- Added new method fileScanInStream (resolves #21)

### CODE REVIEW

**Comment by SoftCreatR** [comment]
The tests will fail until https://github.com/appwrite/docker-clamav/pull/21 has been merged.

**Comment by nadar** [comment]
+1 for this PR, because it seems that the new function `fileScanInStream` allows me to send a file by its "content" on not by its filepath which requires to have file on the clamav server. This is a huge advantage at makes it easy to work when using dockerized setup.

(@SoftCreatR correct me if im wrong :smile:)

**Comment by SoftCreatR** [comment]
That's correct.

**Comment by TorstenDittmann** [comment]
@SoftCreatR `appwrite/clamav:latest` is pushed on Docker with your changes 👍🏻

**Comment by TorstenDittmann** [comment]
Multiarch image also ready with `appwrite/clamav:2.0.0` 👍🏻

**Comment by nadar** [comment]
Would be nice to see this merged soon :peace_symbol:. I could contribute a PR with a real world usage example when using docker-compose

**Comment by nadar** [comment]
@TorstenDittmann is there any reason to not merge this? If so, i will go forward with a fork :-) Thanks for reply

**Comment by nadar** [comment]
If someon else is looking for this, sadly we had to publish a fork on packagist: https://github.com/flyocloud/php-clamav -> https://packagist.org/packages/flyocloud/php-clamav

**Review by TorstenDittmann — APPROVED** [review]

**Pull request merged**
