### PR TITLE
Code overhaul

### PR DESCRIPTION
**Pull request by SoftCreatR**
- Change fully-qualified function calls to namespaced function calls for simplicity. However, the performance gain is so little, that they could be completely removed.
- Declare visibility for constants
- Add return type hints
- Perform small code optimizations
- Format files
- Add missing dependency "ext-sockets" to composer.json
- Update test namespace
- Replace Travis CI with GitHub Action

### CODE REVIEW

**Comment by eldadfux** [comment]
@SoftCreatR thanks for the PR. All changes looks great. Please keep the Travis CI file. We currently use travis for all our repos (+50) and any change to that will have to be accepted and planned for all our repos.

**Comment by SoftCreatR** [comment]
Okay, no problem. Want me to completely remove the GitHub action, or leave it there?

**Comment by eldadfux** [comment]
For now you can just remove it, thanks!

**Comment by SoftCreatR** [comment]
Done ;)

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Comment by eldadfux** [comment]
@SoftCreatR if you wish to contribute more on our PHP codebase, feel free to check our https://github.com/utopia-php namespace, we got lots of PHP libraries there :)

**Comment by SoftCreatR** [comment]
> @SoftCreatR if you wish to contribute more on our PHP codebase, feel free to check our https://github.com/utopia-php namespace, we got lots of PHP libraries there :)

That's already on my to-do. However, please don't forget the corresponding Docker container update, that I've pushed, too 😎

**Pull request merged**
